# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 1
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

    # Limiter le nombre de PR ouverts simultanément
    open-pull-requests-limit: 10

    # Étiquettes pour les PR
    labels:
      - "dependencies"

    # Stratégie de versioning
    versioning-strategy: auto

    # Grouper les mises à jour mineures et de patch
    groups:
      dev-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "actions"
